---
# Ansible Galaxy requirements
collections:
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: amazon.aws
    version: ">=6.0.0"
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
